name: Add topics to repos by org

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  add-topics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    
    - name: Add topics
      run: |
        export GITHUB_TOKEN=${{ secrets.OWNER_TOKEN }}
        export GITHUB_ORG=${{ env.REPO_OWNER }}
        make configure
        make build
        make run
        